### PR TITLE
fixes centering issues

### PR DESCRIPTION
**Pull request by Thomaswaters05**
These changes are not 100% mobile friendly but will fix it to the best of ability due to the soundcloud/blockquote attributes. Double check this, but should be golden.

### CODE REVIEW

**Comment by debragordon** [comment]
@Thomaswaters05 ... can you fix the H1 font size?  It isn't consistent with the about page.  on the About Page, the h1 header "About the Producer is an H1 and it is 2em.  On your page, for some reason when I review it with the dev tools it is turned off and it is smaller than what is showing up on the about page.

**Comment by Thomaswaters05** [comment]
Debra- The newest branch fixes the font size and has the changes for the centering as well. When I pushed to github- I only added/changed my css/samples.css. I just want to confirm that is correct.

**Comment by debragordon** [comment]
ok 👍 will merge now

**Comment by JoeShep** [comment]
Team, make sure that the person who submits the PR is who merges the code. Reviewers give the thumbs-up, but the author of the code does the merge. That way, each dev is responsible for their code from beginning to end

**Comment by debragordon** [comment]
@JoeShep good point ... we are all getting used to this git world and versions of code.  Thanks for giving us best practices!

**Pull request merged**
